# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gt/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/gt/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gt/iiit/graphics/a1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gt/iiit/graphics/a1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gt/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gt/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gt/iiit/graphics/a1/CMakeFiles /home/gt/iiit/graphics/a1/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gt/iiit/graphics/a1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AmongUs

# Build rule for target.
AmongUs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AmongUs
.PHONY : AmongUs

# fast build rule for target.
AmongUs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/build
.PHONY : AmongUs/fast

glad.o: glad.c.o

.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i

.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s

.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/glad.c.s
.PHONY : glad.c.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/game_maze.o: src/game_maze.cpp.o

.PHONY : src/game_maze.o

# target to build an object file
src/game_maze.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_maze.cpp.o
.PHONY : src/game_maze.cpp.o

src/game_maze.i: src/game_maze.cpp.i

.PHONY : src/game_maze.i

# target to preprocess a source file
src/game_maze.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_maze.cpp.i
.PHONY : src/game_maze.cpp.i

src/game_maze.s: src/game_maze.cpp.s

.PHONY : src/game_maze.s

# target to generate assembly for a file
src/game_maze.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_maze.cpp.s
.PHONY : src/game_maze.cpp.s

src/game_object.o: src/game_object.cpp.o

.PHONY : src/game_object.o

# target to build an object file
src/game_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_object.cpp.o
.PHONY : src/game_object.cpp.o

src/game_object.i: src/game_object.cpp.i

.PHONY : src/game_object.i

# target to preprocess a source file
src/game_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_object.cpp.i
.PHONY : src/game_object.cpp.i

src/game_object.s: src/game_object.cpp.s

.PHONY : src/game_object.s

# target to generate assembly for a file
src/game_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_object.cpp.s
.PHONY : src/game_object.cpp.s

src/game_room.o: src/game_room.cpp.o

.PHONY : src/game_room.o

# target to build an object file
src/game_room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_room.cpp.o
.PHONY : src/game_room.cpp.o

src/game_room.i: src/game_room.cpp.i

.PHONY : src/game_room.i

# target to preprocess a source file
src/game_room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_room.cpp.i
.PHONY : src/game_room.cpp.i

src/game_room.s: src/game_room.cpp.s

.PHONY : src/game_room.s

# target to generate assembly for a file
src/game_room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/game_room.cpp.s
.PHONY : src/game_room.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/resource_manager.o: src/resource_manager.cpp.o

.PHONY : src/resource_manager.o

# target to build an object file
src/resource_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/resource_manager.cpp.o
.PHONY : src/resource_manager.cpp.o

src/resource_manager.i: src/resource_manager.cpp.i

.PHONY : src/resource_manager.i

# target to preprocess a source file
src/resource_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/resource_manager.cpp.i
.PHONY : src/resource_manager.cpp.i

src/resource_manager.s: src/resource_manager.cpp.s

.PHONY : src/resource_manager.s

# target to generate assembly for a file
src/resource_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/resource_manager.cpp.s
.PHONY : src/resource_manager.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/sprite_renderer.o: src/sprite_renderer.cpp.o

.PHONY : src/sprite_renderer.o

# target to build an object file
src/sprite_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/sprite_renderer.cpp.o
.PHONY : src/sprite_renderer.cpp.o

src/sprite_renderer.i: src/sprite_renderer.cpp.i

.PHONY : src/sprite_renderer.i

# target to preprocess a source file
src/sprite_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/sprite_renderer.cpp.i
.PHONY : src/sprite_renderer.cpp.i

src/sprite_renderer.s: src/sprite_renderer.cpp.s

.PHONY : src/sprite_renderer.s

# target to generate assembly for a file
src/sprite_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/sprite_renderer.cpp.s
.PHONY : src/sprite_renderer.cpp.s

src/stb_image.o: src/stb_image.cpp.o

.PHONY : src/stb_image.o

# target to build an object file
src/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/stb_image.cpp.o
.PHONY : src/stb_image.cpp.o

src/stb_image.i: src/stb_image.cpp.i

.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s

.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

src/task.o: src/task.cpp.o

.PHONY : src/task.o

# target to build an object file
src/task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/task.cpp.o
.PHONY : src/task.cpp.o

src/task.i: src/task.cpp.i

.PHONY : src/task.i

# target to preprocess a source file
src/task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/task.cpp.i
.PHONY : src/task.cpp.i

src/task.s: src/task.cpp.s

.PHONY : src/task.s

# target to generate assembly for a file
src/task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/task.cpp.s
.PHONY : src/task.cpp.s

src/text_renderer.o: src/text_renderer.cpp.o

.PHONY : src/text_renderer.o

# target to build an object file
src/text_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/text_renderer.cpp.o
.PHONY : src/text_renderer.cpp.o

src/text_renderer.i: src/text_renderer.cpp.i

.PHONY : src/text_renderer.i

# target to preprocess a source file
src/text_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/text_renderer.cpp.i
.PHONY : src/text_renderer.cpp.i

src/text_renderer.s: src/text_renderer.cpp.s

.PHONY : src/text_renderer.s

# target to generate assembly for a file
src/text_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/text_renderer.cpp.s
.PHONY : src/text_renderer.cpp.s

src/texture.o: src/texture.cpp.o

.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i

.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s

.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AmongUs.dir/build.make CMakeFiles/AmongUs.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AmongUs"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/game_maze.o"
	@echo "... src/game_maze.i"
	@echo "... src/game_maze.s"
	@echo "... src/game_object.o"
	@echo "... src/game_object.i"
	@echo "... src/game_object.s"
	@echo "... src/game_room.o"
	@echo "... src/game_room.i"
	@echo "... src/game_room.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/resource_manager.o"
	@echo "... src/resource_manager.i"
	@echo "... src/resource_manager.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/sprite_renderer.o"
	@echo "... src/sprite_renderer.i"
	@echo "... src/sprite_renderer.s"
	@echo "... src/stb_image.o"
	@echo "... src/stb_image.i"
	@echo "... src/stb_image.s"
	@echo "... src/task.o"
	@echo "... src/task.i"
	@echo "... src/task.s"
	@echo "... src/text_renderer.o"
	@echo "... src/text_renderer.i"
	@echo "... src/text_renderer.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

